before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - "export OF_REFRESHTOKEN=$OF_REFRESHTOKEN"

install:
    - "wget -O addon-sdk.tar.gz https://ftp.mozilla.org/pub/mozilla.org/labs/jetpack/addon-sdk-1.12.tar.gz"
    - "tar -xf addon-sdk.tar.gz"
    - "alias cfx=`pwd`/addon-sdk-1.12/bin/cfx"

script: 
    - "$HOME/build/ohtufox/helloworld/addon-sdk-1.12/bin/cfx test"
    - "€HOME/build/ohtufox/helloworld/addon-sdk-1.12/bin/cfx xpi"
    - ./script.sh

notifications:
  irc:
    channels:
        - "irc.freenode.org#travistestin"
        - "irc.mozilla.org#travistesting"
        - "irc.cc.tut.fi#travistesting"
    use_notice: true
  email: true
  
env:
  global:
    secure: "kEbpbQQMU/mRpgvkHh53qDi9Po25amSi9UJ4nDW4fkFSQvOBDShPBAvW2Sg3\nPkwTq2Y5vHEb7VQ0zCmYwgs/x+qA2JAJclo6FLyZaOXuZokDHMp4OC9fyPdJ\nVT+R2GX3k4gBjYC7q1n+XW5d+ydlQ/WdEoBlc+FMCSEoIq4hjTg="
