before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

language: node_js

test: cfx test
install:
    - wget -O addon-sdk.tar.gz https://ftp.mozilla.org/pub/mozilla.org/labs/jetpack/addon-sdk-1.12.tar.gz
    - tar -xf addon-sdk.tar.gz
    - ln -s addon-sdk-1.12/bin/cfx ~/bin/cfx
script: cfx xpi
